name: Deploy to Staging

on:
    push:
        branches:
            - staging

jobs:
    redeploy_everything:
        runs-on: ubuntu-latest
        name: Deploying to staging server

        steps:
            - name: Set up SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.STAGING_SERVER_IP }} >> ~/.ssh/known_hosts

            - name: Deploy over SSH
              run: |
                  ssh ubuntu@${{ secrets.STAGING_SERVER_IP }} "bash -lc '
                    cd carbontrace
                    nvm use --lts
                    pnpm install
                    pnpm build
                    pm2 restart all 
                    '"

